
/* File generated by FTEQCC, relevent for engine modding only, the generated crc must be the same as your engine expects. */

typedef struct globalvars_s
{	int pad;
	int ofs_return[3];
	int ofs_parm0[3];
	int ofs_parm1[3];
	int ofs_parm2[3];
	int ofs_parm3[3];
	int ofs_parm4[3];
	int ofs_parm5[3];
	int ofs_parm6[3];
	int ofs_parm7[3];
	int	self;
	int	other;
	int	world;
	float	time;
	float	frametime;
	float	force_retouch;
	string_t	mapname;
	float	deathmatch;
	float	coop;
	float	teamplay;
	float	serverflags;
	float	total_secrets;
	float	total_monsters;
	float	found_secrets;
	float	killed_monsters;
	float	parm1;
	float	parm2;
	float	parm3;
	float	parm4;
	float	parm5;
	float	parm6;
	float	parm7;
	float	parm8;
	float	parm9;
	float	parm10;
	float	parm11;
	float	parm12;
	float	parm13;
	float	parm14;
	float	parm15;
	float	parm16;
	vec3_t	v_forward;
	vec3_t	v_up;
	vec3_t	v_right;
	float	trace_allsolid;
	float	trace_startsolid;
	float	trace_fraction;
	vec3_t	trace_endpos;
	vec3_t	trace_plane_normal;
	float	trace_plane_dist;
	int	trace_ent;
	float	trace_inopen;
	float	trace_inwater;
	int	msg_entity;
	func_t	main;
	func_t	StartFrame;
	func_t	EndFrame;
	func_t	PlayerPreThink;
	func_t	PlayerPostThink;
	func_t	ClientKill;
	func_t	ClientConnect;
	func_t	PutClientInServer;
	func_t	ClientDisconnect;
	func_t	SetNewParms;
	func_t	SetChangeParms;
} globalvars_t;

typedef struct entvars_s
{
	float	modelindex;
	vec3_t	absmin;
	vec3_t	absmax;
	float	ltime;
	float	movetype;
	float	solid;
	vec3_t	origin;
	vec3_t	oldorigin;
	vec3_t	velocity;
	vec3_t	angles;
	vec3_t	avelocity;
	vec3_t	punchangle;
	string_t	classname;
	string_t	model;
	float	frame;
	float	skin;
	float	body;
	float	effects;
	float	sequence;
	float	renderfx;
	vec3_t	mins;
	vec3_t	maxs;
	vec3_t	size;
	func_t	touch;
	func_t	use;
	func_t	think;
	func_t	blocked;
	float	nextthink;
	int	groundentity;
	float	health;
	float	frags;
	float	weapon;
	string_t	weaponmodel;
	float	weaponframe;
	float	currentammo;
	float	ammo_shells;
	float	ammo_nails;
	float	ammo_rockets;
	float	ammo_cells;
	float	items;
	float	takedamage;
	int	chain;
	float	deadflag;
	vec3_t	view_ofs;
	float	button0;
	float	button1;
	float	button2;
	float	impulse;
	float	fixangle;
	vec3_t	v_angle;
	float	idealpitch;
	string_t	netname;
	int	enemy;
	float	flags;
	float	colormap;
	float	team;
	float	max_health;
	float	teleport_time;
	float	armortype;
	float	armorvalue;
	float	waterlevel;
	float	watertype;
	float	ideal_yaw;
	float	yaw_speed;
	int	aiment;
	int	goalentity;
	float	spawnflags;
	string_t	target;
	string_t	targetname;
	float	dmg_take;
	float	dmg_save;
	int	dmg_inflictor;
	int	owner;
	vec3_t	movedir;
	string_t	message;
	float	sounds;
	string_t	noise;
	string_t	noise1;
	string_t	noise2;
	string_t	noise3;
} entvars_t;

//with this the crc isn't needed for fields.
struct fieldvars_s
{
	int ofs;
	int type;
	char *name;
} fieldvars[] = {
	{0,	2,	"modelindex"},
	{1,	3,	"absmin"},
	{1,	2,	"absmin_x"},
	{2,	2,	"absmin_y"},
	{3,	2,	"absmin_z"},
	{4,	3,	"absmax"},
	{4,	2,	"absmax_x"},
	{5,	2,	"absmax_y"},
	{6,	2,	"absmax_z"},
	{7,	2,	"ltime"},
	{8,	2,	"movetype"},
	{9,	2,	"solid"},
	{10,	3,	"origin"},
	{10,	2,	"origin_x"},
	{11,	2,	"origin_y"},
	{12,	2,	"origin_z"},
	{13,	3,	"oldorigin"},
	{13,	2,	"oldorigin_x"},
	{14,	2,	"oldorigin_y"},
	{15,	2,	"oldorigin_z"},
	{16,	3,	"velocity"},
	{16,	2,	"velocity_x"},
	{17,	2,	"velocity_y"},
	{18,	2,	"velocity_z"},
	{19,	3,	"angles"},
	{19,	2,	"angles_x"},
	{20,	2,	"angles_y"},
	{21,	2,	"angles_z"},
	{22,	3,	"avelocity"},
	{22,	2,	"avelocity_x"},
	{23,	2,	"avelocity_y"},
	{24,	2,	"avelocity_z"},
	{25,	3,	"punchangle"},
	{25,	2,	"punchangle_x"},
	{26,	2,	"punchangle_y"},
	{27,	2,	"punchangle_z"},
	{28,	1,	"classname"},
	{29,	1,	"model"},
	{30,	2,	"frame"},
	{31,	2,	"skin"},
	{32,	2,	"body"},
	{33,	2,	"effects"},
	{34,	2,	"sequence"},
	{35,	2,	"renderfx"},
	{36,	3,	"mins"},
	{36,	2,	"mins_x"},
	{37,	2,	"mins_y"},
	{38,	2,	"mins_z"},
	{39,	3,	"maxs"},
	{39,	2,	"maxs_x"},
	{40,	2,	"maxs_y"},
	{41,	2,	"maxs_z"},
	{42,	3,	"size"},
	{42,	2,	"size_x"},
	{43,	2,	"size_y"},
	{44,	2,	"size_z"},
	{45,	6,	"touch"},
	{46,	6,	"use"},
	{47,	6,	"think"},
	{48,	6,	"blocked"},
	{49,	2,	"nextthink"},
	{50,	4,	"groundentity"},
	{51,	2,	"health"},
	{52,	2,	"frags"},
	{53,	2,	"weapon"},
	{54,	1,	"weaponmodel"},
	{55,	2,	"weaponframe"},
	{56,	2,	"currentammo"},
	{57,	2,	"ammo_shells"},
	{58,	2,	"ammo_nails"},
	{59,	2,	"ammo_rockets"},
	{60,	2,	"ammo_cells"},
	{61,	2,	"items"},
	{62,	2,	"takedamage"},
	{63,	4,	"chain"},
	{64,	2,	"deadflag"},
	{65,	3,	"view_ofs"},
	{65,	2,	"view_ofs_x"},
	{66,	2,	"view_ofs_y"},
	{67,	2,	"view_ofs_z"},
	{68,	2,	"button0"},
	{69,	2,	"button1"},
	{70,	2,	"button2"},
	{71,	2,	"impulse"},
	{72,	2,	"fixangle"},
	{73,	3,	"v_angle"},
	{73,	2,	"v_angle_x"},
	{74,	2,	"v_angle_y"},
	{75,	2,	"v_angle_z"},
	{76,	2,	"idealpitch"},
	{77,	1,	"netname"},
	{78,	4,	"enemy"},
	{79,	2,	"flags"},
	{80,	2,	"colormap"},
	{81,	2,	"team"},
	{82,	2,	"max_health"},
	{83,	2,	"teleport_time"},
	{84,	2,	"armortype"},
	{85,	2,	"armorvalue"},
	{86,	2,	"waterlevel"},
	{87,	2,	"watertype"},
	{88,	2,	"ideal_yaw"},
	{89,	2,	"yaw_speed"},
	{90,	4,	"aiment"},
	{91,	4,	"goalentity"},
	{92,	2,	"spawnflags"},
	{93,	1,	"target"},
	{94,	1,	"targetname"},
	{95,	2,	"dmg_take"},
	{96,	2,	"dmg_save"},
	{97,	4,	"dmg_inflictor"},
	{98,	4,	"owner"},
	{99,	3,	"movedir"},
	{99,	2,	"movedir_x"},
	{100,	2,	"movedir_y"},
	{101,	2,	"movedir_z"},
	{102,	1,	"message"},
	{103,	2,	"sounds"},
	{104,	1,	"noise"},
	{105,	1,	"noise1"},
	{106,	1,	"noise2"},
	{107,	1,	"noise3"}
};

#define PROGHEADER_CRC 21645
