
// progdefs.h
// generated by Xash3D QuakeC compiler

#ifndef PROGDEFS_H
#define PROGDEFS_H

typedef struct globalvars_s
{
	int	pad[28];
	int	pev;
	int	other;
	int	world;
	float	time;
	float	frametime;
	string_t	mapname;
	string_t	startspot;
	vec3_t	spotoffset;
	float	deathmatch;
	float	coop;
	float	teamplay;
	float	serverflags;
	float	total_secrets;
	float	total_monsters;
	float	found_secrets;
	float	killed_monsters;
	vec3_t	v_forward;
	vec3_t	v_right;
	vec3_t	v_up;
	float	trace_allsolid;
	float	trace_startsolid;
	float	trace_fraction;
	vec3_t	trace_endpos;
	vec3_t	trace_plane_normal;
	float	trace_plane_dist;
	float	trace_hitgroup;
	float	trace_contents;
	int	trace_ent;
	float	trace_flags;
	func_t	main;
	func_t	StartFrame;
	func_t	EndFrame;
	func_t	PlayerPreThink;
	func_t	PlayerPostThink;
	func_t	ClientKill;
	func_t	ClientConnect;
	func_t	PutClientInServer;
	func_t	ClientDisconnect;
	func_t	ClientCommand;
} globalvars_t;

typedef struct entvars_s
{
	string_t	classname;
	string_t	globalname;
	float	modelindex;
	vec3_t	origin;
	vec3_t	angles;
	vec3_t	old_origin;
	vec3_t	old_angles;
	vec3_t	velocity;
	vec3_t	avelocity;
	vec3_t	m_pmatrix;
	vec3_t	m_pmatrix[1];
	vec3_t	m_pmatrix[2];
	vec3_t	m_pmatrix[3];
	vec3_t	m_pcentre;
	vec3_t	m_pcentre[1];
	vec3_t	m_pcentre[2];
	vec3_t	torque;
	vec3_t	force;
	vec3_t	post_origin;
	vec3_t	post_angles;
	vec3_t	origin_offset;
	float	ltime;
	float	bouncetype;
	float	movetype;
	float	solid;
	vec3_t	absmin;
	vec3_t	absmax;
	vec3_t	mins;
	vec3_t	maxs;
	vec3_t	size;
	int	chain;
	string_t	model;
	float	frame;
	float	sequence;
	float	renderfx;
	float	effects;
	float	skin;
	float	body;
	string_t	weaponmodel;
	float	weaponframe;
	func_t	use;
	func_t	touch;
	func_t	think;
	func_t	blocked;
	func_t	activate;
	func_t	walk;
	func_t	jump;
	func_t	duck;
	float	flags;
	float	aiflags;
	float	spawnflags;
	int	groundentity;
	float	nextthink;
	float	takedamage;
	float	health;
	float	frags;
	float	weapon;
	float	items;
	string_t	target;
	string_t	parent;
	string_t	targetname;
	int	aiment;
	int	goalentity;
	vec3_t	punchangle;
	float	deadflag;
	vec3_t	view_ofs;
	float	button0;
	float	button1;
	float	button2;
	float	impulse;
	float	fixangle;
	vec3_t	v_angle;
	float	idealpitch;
	string_t	netname;
	int	enemy;
	float	alpha;
	float	team;
	float	max_health;
	float	teleport_time;
	float	armortype;
	float	armorvalue;
	float	waterlevel;
	float	watertype;
	float	ideal_yaw;
	float	yaw_speed;
	float	dmg_take;
	float	dmg_save;
	int	dmg_inflictor;
	int	owner;
	vec3_t	movedir;
	string_t	message;
	float	sounds;
	string_t	noise;
	string_t	noise1;
	string_t	noise2;
	string_t	noise3;
	float	jumpup;
	float	jumpdn;
	int	movetarget;
	float	mass;
	float	density;
	float	gravity;
	float	dmg;
	float	dmgtime;
	float	speed;
} entvars_t;


#define REQFIELDS (sizeof(reqfields) / sizeof(fields_t))

static fields_t reqfields[] = 
{
	{159,	6,	"th_stand"},
	{160,	6,	"th_walk"},
	{161,	6,	"th_run"},
	{162,	6,	"th_pain"},
	{163,	6,	"th_die"},
	{164,	6,	"th_missile"},
	{165,	6,	"th_melee"},
	{166,	1,	"wad"},
	{167,	1,	"map"},
	{168,	1,	"landmark"},
	{169,	2,	"worldtype"},
	{170,	2,	"delay"},
	{171,	2,	"wait"},
	{172,	2,	"lip"},
	{173,	2,	"light_lev"},
	{174,	2,	"style"},
	{175,	2,	"skill"},
	{176,	1,	"killtarget"},
	{177,	3,	"pos1"},
	{180,	3,	"pos2"},
	{183,	3,	"mangle"},
	{186,	2,	"pain_finished"},
	{187,	2,	"air_finished"},
	{188,	3,	"camview"},
	{191,	2,	"aflag"},
	{192,	4,	"trigger_field"},
	{193,	2,	"anim_time"},
	{194,	2,	"anim_end"},
	{195,	2,	"anim_priority"},
	{196,	2,	"anim_run"},
	{197,	2,	"showhelp"},
	{198,	2,	"showinventory"},
	{199,	2,	"touched"},
	{200,	1,	"name"},
	{201,	4,	"triggerer"},
	{202,	1,	"targ"},
	{203,	1,	"targ[1]"},
	{204,	1,	"targ[2]"},
	{205,	1,	"targ[3]"},
	{206,	1,	"targ[4]"},
	{207,	1,	"targ[5]"},
	{208,	1,	"targ[6]"},
	{209,	1,	"targ[7]"},
	{210,	1,	"oldtarg"},
	{211,	1,	"oldtarg[1]"},
	{212,	1,	"oldtarg[2]"},
	{213,	1,	"oldtarg[3]"},
	{214,	1,	"oldtarg[4]"},
	{215,	1,	"oldtarg[5]"},
	{216,	1,	"oldtarg[6]"},
	{217,	1,	"oldtarg[7]"},
	{218,	2,	"twait"},
	{219,	2,	"twait[1]"},
	{220,	2,	"twait[2]"},
	{221,	2,	"twait[3]"},
	{222,	2,	"twait[4]"},
	{223,	2,	"twait[5]"},
	{224,	2,	"twait[6]"},
	{225,	2,	"twait[7]"},
	{226,	2,	"olddelay"},
	{227,	1,	"message1"},
	{228,	1,	"message2"},
	{229,	2,	"count"},
	{230,	2,	"state"},
	{231,	2,	"used"},
	{232,	3,	"dest"},
	{235,	1,	"target_dest"},
	{236,	1,	"oldmodel"}
};

#define PROG_CRC_SERVER	6477

#endif//PROGDEFS_H