
// progdefs.h
// generated by Xash3D QuakeC compiler

#ifndef PROGDEFS_H
#define PROGDEFS_H

typedef struct globalvars_s
{
	int	pad[28];
	int	pev;
	int	other;
	int	world;
	float	time;
	float	frametime;
	string_t	mapname;
	string_t	startspot;
	vec3_t	spotoffset;
	float	deathmatch;
	float	coop;
	float	teamplay;
	float	serverflags;
	float	total_secrets;
	float	total_monsters;
	float	found_secrets;
	float	killed_monsters;
	vec3_t	v_forward;
	vec3_t	v_right;
	vec3_t	v_up;
	float	trace_allsolid;
	float	trace_startsolid;
	float	trace_fraction;
	vec3_t	trace_endpos;
	vec3_t	trace_plane_normal;
	float	trace_plane_dist;
	float	trace_hitgroup;
	float	trace_contents;
	int	trace_ent;
	float	trace_flags;
	func_t	main;
	func_t	StartFrame;
	func_t	EndFrame;
	func_t	PlayerPreThink;
	func_t	PlayerPostThink;
	func_t	ClientKill;
	func_t	ClientConnect;
	func_t	PutClientInServer;
	func_t	ClientDisconnect;
	func_t	ClientCommand;
} globalvars_t;

typedef struct entvars_s
{
	string_t	classname;
	string_t	globalname;
	float	modelindex;
	vec3_t	origin;
	vec3_t	angles;
	vec3_t	old_origin;
	vec3_t	old_angles;
	vec3_t	velocity;
	vec3_t	avelocity;
	vec3_t	post_origin;
	vec3_t	post_angles;
	vec3_t	post_velocity;
	vec3_t	post_avelocity;
	vec3_t	origin_offset;
	vec3_t	angles_offset;
	float	ltime;
	float	bouncetype;
	float	movetype;
	float	solid;
	vec3_t	absmin;
	vec3_t	absmax;
	vec3_t	mins;
	vec3_t	maxs;
	vec3_t	size;
	int	chain;
	string_t	model;
	float	frame;
	float	sequence;
	float	renderfx;
	float	effects;
	float	skin;
	float	body;
	string_t	weaponmodel;
	float	weaponframe;
	func_t	use;
	func_t	touch;
	func_t	think;
	func_t	blocked;
	func_t	activate;
	func_t	walk;
	func_t	jump;
	func_t	duck;
	float	flags;
	float	aiflags;
	float	spawnflags;
	int	groundentity;
	float	nextthink;
	float	takedamage;
	float	health;
	float	frags;
	float	weapon;
	float	items;
	string_t	target;
	string_t	parent;
	string_t	targetname;
	int	aiment;
	int	goalentity;
	vec3_t	punchangle;
	float	deadflag;
	vec3_t	view_ofs;
	float	button0;
	float	button1;
	float	button2;
	float	impulse;
	float	fixangle;
	vec3_t	v_angle;
	float	idealpitch;
	string_t	netname;
	int	enemy;
	float	alpha;
	float	team;
	float	max_health;
	float	teleport_time;
	float	armortype;
	float	armorvalue;
	float	waterlevel;
	float	watertype;
	float	ideal_yaw;
	float	yaw_speed;
	float	dmg_take;
	float	dmg_save;
	int	dmg_inflictor;
	int	owner;
	vec3_t	movedir;
	string_t	message;
	float	sounds;
	string_t	noise;
	string_t	noise1;
	string_t	noise2;
	string_t	noise3;
	float	jumpup;
	float	jumpdn;
	int	movetarget;
	float	mass;
	float	density;
	float	gravity;
	float	dmg;
	float	dmgtime;
	float	speed;
} entvars_t;


typedef struct prvm_fieldvars_s
{
	int		ofs;
	int		type;
	const char	*name;
} prvm_fieldvars_t;

#define REQFIELDS (sizeof(reqfields) / sizeof(prvm_fieldvars_t))

static prvm_fieldvars_t reqfields[] = 
{
	{0,	1,	"classname"},
	{1,	1,	"globalname"},
	{2,	2,	"modelindex"},
	{3,	3,	"origin"},
	{6,	3,	"angles"},
	{9,	3,	"old_origin"},
	{12,	3,	"old_angles"},
	{15,	3,	"velocity"},
	{18,	3,	"avelocity"},
	{21,	3,	"post_origin"},
	{24,	3,	"post_angles"},
	{27,	3,	"post_velocity"},
	{30,	3,	"post_avelocity"},
	{33,	3,	"origin_offset"},
	{36,	3,	"angles_offset"},
	{39,	2,	"ltime"},
	{40,	2,	"bouncetype"},
	{41,	2,	"movetype"},
	{42,	2,	"solid"},
	{43,	3,	"absmin"},
	{46,	3,	"absmax"},
	{49,	3,	"mins"},
	{52,	3,	"maxs"},
	{55,	3,	"size"},
	{58,	4,	"chain"},
	{59,	1,	"model"},
	{60,	2,	"frame"},
	{61,	2,	"sequence"},
	{62,	2,	"renderfx"},
	{63,	2,	"effects"},
	{64,	2,	"skin"},
	{65,	2,	"body"},
	{66,	1,	"weaponmodel"},
	{67,	2,	"weaponframe"},
	{68,	6,	"use"},
	{69,	6,	"touch"},
	{70,	6,	"think"},
	{71,	6,	"blocked"},
	{72,	6,	"activate"},
	{73,	6,	"walk"},
	{74,	6,	"jump"},
	{75,	6,	"duck"},
	{76,	2,	"flags"},
	{77,	2,	"aiflags"},
	{78,	2,	"spawnflags"},
	{79,	4,	"groundentity"},
	{80,	2,	"nextthink"},
	{81,	2,	"takedamage"},
	{82,	2,	"health"},
	{83,	2,	"frags"},
	{84,	2,	"weapon"},
	{85,	2,	"items"},
	{86,	1,	"target"},
	{87,	1,	"parent"},
	{88,	1,	"targetname"},
	{89,	4,	"aiment"},
	{90,	4,	"goalentity"},
	{91,	3,	"punchangle"},
	{94,	2,	"deadflag"},
	{95,	3,	"view_ofs"},
	{98,	2,	"button0"},
	{99,	2,	"button1"},
	{100,	2,	"button2"},
	{101,	2,	"impulse"},
	{102,	2,	"fixangle"},
	{103,	3,	"v_angle"},
	{106,	2,	"idealpitch"},
	{107,	1,	"netname"},
	{108,	4,	"enemy"},
	{109,	2,	"alpha"},
	{110,	2,	"team"},
	{111,	2,	"max_health"},
	{112,	2,	"teleport_time"},
	{113,	2,	"armortype"},
	{114,	2,	"armorvalue"},
	{115,	2,	"waterlevel"},
	{116,	2,	"watertype"},
	{117,	2,	"ideal_yaw"},
	{118,	2,	"yaw_speed"},
	{119,	2,	"dmg_take"},
	{120,	2,	"dmg_save"},
	{121,	4,	"dmg_inflictor"},
	{122,	4,	"owner"},
	{123,	3,	"movedir"},
	{126,	1,	"message"},
	{127,	2,	"sounds"},
	{128,	1,	"noise"},
	{129,	1,	"noise1"},
	{130,	1,	"noise2"},
	{131,	1,	"noise3"},
	{132,	2,	"jumpup"},
	{133,	2,	"jumpdn"},
	{134,	4,	"movetarget"},
	{135,	2,	"mass"},
	{136,	2,	"density"},
	{137,	2,	"gravity"},
	{138,	2,	"dmg"},
	{139,	2,	"dmgtime"},
	{140,	2,	"speed"}
};

#define PROG_CRC_SERVER	64081

#endif//PROGDEFS_H